"""add processing metadata

Revision ID: d7d8b2680fa9
Revises: abaa873391c6
Create Date: 2026-06-30 15:41:06.662363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d8b2680fa9'
down_revision: Union[str, Sequence[str], None] = 'abaa873391c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'documents',
    sa.Column(
        'text_length',
        sa.Integer(),
        nullable=False,
        server_default='0'
    )
)
    op.add_column(
    'documents',
    sa.Column(
        'chunk_count',
        sa.Integer(),
        nullable=False,
        server_default='0'
    )
)
    op.add_column(
    'documents',
    sa.Column(
        'processing_error',
        sa.Text(),
        nullable=True
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_error')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'text_length')
    # ### end Alembic commands ###
